"""
Host-independent application services for Wire Bundler workflows.
"""

from .add_pathway import (
    PathwayGateway,
    PathwayUpdateError,
    add_pathway,
    suggest_pathway_name,
)
from .add_standalone_end import (
    StandaloneEndGateway,
    StandaloneEndResult,
    StandaloneEndUpdateError,
    add_standalone_end,
)
from .create_harness import (
    HarnessCreationError,
    HarnessGateway,
    create_empty_harness,
    suggest_harness_name,
)
from .edit_harness import (
    HarnessEditError,
    HarnessEditGateway,
    PathwaySegmentResult,
    add_end_refine,
    add_junction,
    add_junction_relationship,
    add_pathway_refine,
    append_end_guides,
    append_pathway_gates,
    move_pathway_gate,
    remove_junction,
    remove_junction_relationship,
    remove_pathway,
    remove_pathway_gate,
    remove_standalone_end,
    rename_junction,
    rename_pathway,
    rename_standalone_end,
    segment_pathway,
    set_harness_material_defaults,
    set_harness_properties,
    suggest_pathway_extension_name,
    update_junction_relationships,
    update_pathway_refine,
)
from .edit_wire_groups import (
    WireEditorPairing,
    WireEditorRename,
    save_wire_editor,
    set_wire_group_material_overrides,
    set_wire_group_properties,
)
from .load_harnesses import (
    DamagedHarnessGateway,
    HarnessLibraryGateway,
    HarnessLoadResult,
    StoredHarness,
    delete_damaged_harness,
    load_harnesses,
)
from .material_catalog import WireMaterialCatalog, load_wire_material_catalog
from .wire_group_routes import (
    WireGroupControlStep,
    WireGroupRouteLeg,
    plan_wire_group_routes,
)

__all__ = [
    "DamagedHarnessGateway",
    "HarnessCreationError",
    "HarnessEditError",
    "HarnessEditGateway",
    "PathwaySegmentResult",
    "WireEditorPairing",
    "WireEditorRename",
    "WireGroupControlStep",
    "WireGroupRouteLeg",
    "HarnessGateway",
    "HarnessLibraryGateway",
    "HarnessLoadResult",
    "StoredHarness",
    "StandaloneEndGateway",
    "StandaloneEndResult",
    "StandaloneEndUpdateError",
    "WireMaterialCatalog",
    "PathwayGateway",
    "PathwayUpdateError",
    "add_pathway",
    "add_end_refine",
    "add_junction",
    "add_junction_relationship",
    "add_pathway_refine",
    "add_standalone_end",
    "append_pathway_gates",
    "append_end_guides",
    "create_empty_harness",
    "delete_damaged_harness",
    "load_harnesses",
    "move_pathway_gate",
    "plan_wire_group_routes",
    "remove_junction",
    "remove_pathway",
    "remove_pathway_gate",
    "remove_junction_relationship",
    "remove_standalone_end",
    "rename_junction",
    "rename_pathway",
    "rename_standalone_end",
    "save_wire_editor",
    "segment_pathway",
    "set_harness_material_defaults",
    "set_harness_properties",
    "set_wire_group_material_overrides",
    "set_wire_group_properties",
    "update_pathway_refine",
    "update_junction_relationships",
    "load_wire_material_catalog",
    "suggest_harness_name",
    "suggest_pathway_extension_name",
    "suggest_pathway_name",
]
