"""
Focused transactional edits for persisted harness definitions.
"""

from .ends import (
    add_cable_end_connection,
    add_end_refine,
    append_end_guides,
    attach_cable_end,
    remove_cable_end_attachment,
    remove_end_control,
    remove_end_guide,
    remove_standalone_end,
    rename_cable_end_attachment,
    rename_standalone_end,
    set_cable_end_attachment_properties,
    set_cable_end_properties,
    switch_standalone_end,
)
from .junctions import (
    add_junction,
    add_junction_relationship,
    remove_junction,
    remove_junction_relationship,
    rename_junction,
    set_junction_properties,
    suggest_junction_name,
    update_junction_relationships,
)
from .pathways import (
    add_pathway_refine,
    append_pathway_gates,
    move_pathway_gate,
    remove_pathway,
    remove_pathway_gate,
    rename_pathway,
    segment_pathway,
    set_pathway_end_properties,
    set_pathway_properties,
    suggest_pathway_extension_name,
    update_pathway_refine,
)
from .properties import (
    rename_harness,
    set_harness_material_defaults,
    set_harness_properties,
    set_interpolation,
)
from .types import HarnessEditError, HarnessEditGateway, PathwaySegmentResult

__all__ = [
    "HarnessEditError",
    "HarnessEditGateway",
    "PathwaySegmentResult",
    "add_cable_end_connection",
    "add_end_refine",
    "attach_cable_end",
    "add_junction",
    "add_junction_relationship",
    "add_pathway_refine",
    "append_end_guides",
    "append_pathway_gates",
    "move_pathway_gate",
    "remove_junction",
    "remove_junction_relationship",
    "remove_end_control",
    "remove_end_guide",
    "remove_pathway",
    "remove_pathway_gate",
    "remove_standalone_end",
    "remove_cable_end_attachment",
    "rename_cable_end_attachment",
    "rename_harness",
    "rename_junction",
    "rename_pathway",
    "rename_standalone_end",
    "segment_pathway",
    "set_cable_end_attachment_properties",
    "set_cable_end_properties",
    "set_pathway_end_properties",
    "set_pathway_properties",
    "set_harness_material_defaults",
    "set_harness_properties",
    "set_interpolation",
    "set_junction_properties",
    "suggest_junction_name",
    "suggest_pathway_extension_name",
    "switch_standalone_end",
    "update_junction_relationships",
    "update_pathway_refine",
]
